### ISSUE TITLE
Simple fork, exec, file creation and modification tracking

### ISSUE THREAD

**Issue by krs85** [upenn-acg/ProcessCache#1]
For now, let's make the simplest tracker we can. We will print to standard out for now. The IOTracker's purpose is to track inputs and outputs (file system modifications). We can intercept them with ptrace and report them.

- [x] Trace `fork` and print when it happens. Print the new child's pid and the parent's pid.
- [x] Trace `execve` and print when it happens. 
- [x]  Trace whenever a file is created and print info (for now just handle `openat`).
- [x]  Trace whenever a file is modified and print info (for now handle `write`). 
- [x] Trace whenever a file is read and print info (just `read` for now).

TODO Testing

Next:
- [x] Print the arguments for each `execve`. (moving this to its own issue so I'll just mark it done)

Note: broke out the remaining list to their own issues.
